dependencies:
  - name: prometheus
    version: ~8.15.0
    repository: "@stable"
    condition: prometheus.createInstance
  - name: grafana
    version: ~3.7.3
    repository: "@stable"
    condition: grafana.enabled
